[package]
name = "macrdp-audio"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
anyhow = { workspace = true }
tracing = { workspace = true }
tokio = { workspace = true, features = ["sync", "rt"] }
ironrdp-server = "0.10"
ironrdp-rdpsnd = "0.7"
macrdp-capture = { path = "../macrdp-capture" }
